// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Bnk-Ou2WxykGX-XdVV_aJ5Ps43XxSYs',
    appId: '1:269882922686:android:d795fbdeeb3259c1b330ef',
    messagingSenderId: '269882922686',
    projectId: 'running-crew-d3c20',
    databaseURL: 'https://running-crew-d3c20-default-rtdb.firebaseio.com',
    storageBucket: 'running-crew-d3c20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWObVm5Q1KTqqkk0ie29gRhbtFVSq1wkw',
    appId: '1:269882922686:ios:ea060000d2a57c70b330ef',
    messagingSenderId: '269882922686',
    projectId: 'running-crew-d3c20',
    databaseURL: 'https://running-crew-d3c20-default-rtdb.firebaseio.com',
    storageBucket: 'running-crew-d3c20.appspot.com',
    androidClientId: '269882922686-8542ce79ar3t1himtq8ldlhd8960ja5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.runningApp',
  );
}
